post_install() {
    if [ -z `grep -i "^ircd" /etc/group` ]; then
        echo " :: Creating ircd-group"
        groupadd -r ircd
    fi
    if [ -z `grep -i "^ircd" /etc/passwd` ]; then
        echo " :: Creating ircd-user"
        useradd -g ircd -r ircd
    fi

    if [ -d /var/log/ircd/ ]; then 
        chown -R ircd:ircd /var/log/ircd/
    fi

    echo " :: Copy /etc/charybdis/example.conf to /etc/charybdis/ircd.conf to use the example config."
}
